"""
CIC Dataset Preprocessing Module (Shared for IoMT-2024 and Edge-IIoTSet-2022).
============================================================================
Both CIC-BCCC-NRC datasets are generated by CICFlowMeter and share the
same 85-column schema:
  - 4 metadata columns (Flow ID, Src IP, Dst IP, Timestamp) -- dropped
  - 79 numeric flow feature columns (Src Port through Idle Min)
  - 2 label columns: Attack Name (string category), Label (binary 0/1)

Supported datasets:
  - CIC-BCCC-NRC-IoMT-2024: 15 CSV files, ~3.38M rows, Medical IoT traffic
  - CIC-BCCC-NRC-Edge-IIoTSet-2022: 12 CSV files, ~3.23M rows, Industrial IoT traffic

Cross-dataset evaluation is supported because both datasets share identical
feature columns, enabling train-on-one / test-on-other experiments.
============================================================================
"""

import os
import glob
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split


# ============================================================================
# Constants
# ============================================================================

# Metadata columns to drop (not network features)
METADATA_COLS = ['Flow ID', 'Src IP', 'Dst IP', 'Timestamp']

# Label columns
ATTACK_NAME_COL = 'Attack Name'
LABEL_COL = 'Label'

# Dataset directory names
DATASET_DIRS = {
    'iomt': 'CIC-BCCC-NRC-IoMT-2024',
    'iiot': 'CIC-BCCC-NRC-Edge-IIoTSet-2022',
}

# ============================================================================
# IoMT-2024 attack category mapping (for customized distribution)
# Agent 0: Benign + DoS/DDoS attacks
# Agent 1: Benign + MQTT + Recon + MITM attacks
# ============================================================================
IOMT_ATTACK_CATEGORIES = {
    'Benign Traffic': 'Benign',
    # DoS/DDoS group
    'DoS TCP Flood': 'DoS_DDoS',
    'DoS UDP Flood': 'DoS_DDoS',
    'DoS ICMP Flood': 'DoS_DDoS',
    'DDoS ICMP Flood': 'DoS_DDoS',
    'DDoS UDP Flood': 'DoS_DDoS',
    # MQTT + Recon + MITM group
    'MQTT DDoS Publish Flood': 'MQTT_Recon_MITM',
    'MQTT DoS Connect Flood': 'MQTT_Recon_MITM',
    'MQTT DoS Publish Flood': 'MQTT_Recon_MITM',
    'MQTT Malformed': 'MQTT_Recon_MITM',
    'Recon OS Scan': 'MQTT_Recon_MITM',
    'Recon Ping Sweep': 'MQTT_Recon_MITM',
    'Recon Port Scan': 'MQTT_Recon_MITM',
    'Recon Vulnerability Scan': 'MQTT_Recon_MITM',
    'MITM ARP Spoofing': 'MQTT_Recon_MITM',
}

# ============================================================================
# Edge-IIoTSet-2022 attack category mapping (for customized distribution)
# Agent 0: Benign + DDoS/DoS attacks
# Agent 1: Benign + Application-layer attacks
# ============================================================================
IIOT_ATTACK_CATEGORIES = {
    'Benign Traffic': 'Benign',
    # DDoS/DoS group
    'DDoS HTTP Flood': 'DDoS_DoS',
    'DDoS TCP SYN Flood': 'DDoS_DoS',
    # Application attack group
    'SQL Injection': 'Application',
    'XSS': 'Application',
    'Backdoor': 'Application',
    'Ransomware': 'Application',
    'Password Attack': 'Application',
    'Uploading Attack': 'Application',
    'Vulnerability Scanner': 'Application',
    'Port Scanning': 'Application',
    'OS Fingerprinting': 'Application',
}


# ============================================================================
# Data Loading
# ============================================================================

def resolve_cic_dataset_path(data_dir, dataset_name):
    """
    Resolve CIC dataset directory path.

    Searches local paths (data_dir) and common Kaggle input layouts.
    Kaggle normalizes dataset slugs to lowercase-hyphenated, so
    'CIC-BCCC-NRC-IoMT-2024' may appear as 'cic-bccc-nrc-iomt-2024'.

    Args:
        data_dir: Base directory containing dataset folders
        dataset_name: 'iomt' or 'iiot'
    Returns:
        Path to directory containing CSV files
    Raises:
        FileNotFoundError if dataset directory not found
    """
    dir_name = DATASET_DIRS[dataset_name]
    dir_name_lower = dir_name.lower()

    # Explicit candidate paths (most likely first)
    # Kaggle structure: /kaggle/input/<slug>/<OriginalFolderName>/*.csv
    candidates = [
        f'/kaggle/input/{dir_name_lower}/{dir_name}',   # standard Kaggle nested (slug/FolderName)
        f'/kaggle/input/{dir_name}/{dir_name}',         # mixed-case slug variant
        os.path.join(data_dir, dir_name),               # local: ./Dataset/CIC-BCCC-NRC-...
        f'/kaggle/input/{dir_name_lower}',              # flat Kaggle (CSVs directly in slug folder)
        os.path.join(data_dir, dataset_name),
        f'/kaggle/input/{dataset_name}',
    ]

    def _has_csvs(path):
        return os.path.isdir(path) and any(
            f.endswith('.csv') for f in os.listdir(path)
        )

    for path in candidates:
        if _has_csvs(path):
            return path

    # Fuzzy search: scan /kaggle/input and data_dir for matching subdirectories
    search_bases = ['/kaggle/input', data_dir]
    match_substrings = [dir_name_lower, dataset_name]

    for base in search_bases:
        if not os.path.isdir(base):
            continue
        for d in os.listdir(base):
            d_lower = d.lower()
            if not any(s in d_lower for s in match_substrings):
                continue
            full = os.path.join(base, d)
            # Check directory itself
            if _has_csvs(full):
                return full
            # Check one level deeper (e.g. /kaggle/input/slug/ActualDir/)
            if os.path.isdir(full):
                for sd in os.listdir(full):
                    subfull = os.path.join(full, sd)
                    if _has_csvs(subfull):
                        return subfull

    # List available datasets for debugging
    kaggle_input = '/kaggle/input'
    available = ''
    if os.path.isdir(kaggle_input):
        dirs = sorted(os.listdir(kaggle_input))
        available = '\n  Available in /kaggle/input: ' + ', '.join(dirs[:20])

    raise FileNotFoundError(
        f"Could not find {dir_name} dataset.\n"
        f"  Expected a directory with CSV files.\n"
        f"  Searched: {candidates}{available}"
    )


def load_cic_dataset(dataset_dir, subsample_per_file=None, seed=42):
    """
    Load all CSV files from a CIC dataset directory, concatenate into one DataFrame.

    Per-file subsampling caps the number of rows loaded from each CSV, which
    naturally reduces class imbalance (dominant classes get capped while small
    classes remain at full size).

    Args:
        dataset_dir: Path to directory containing CSV files
        subsample_per_file: Max rows per CSV file (None = load all)
        seed: Random seed for subsampling
    Returns:
        combined_df: Combined DataFrame with all data
    """
    csv_files = sorted(glob.glob(os.path.join(dataset_dir, '*.csv')))
    if not csv_files:
        raise FileNotFoundError(f"No CSV files found in {dataset_dir}")

    rng = np.random.default_rng(seed)
    frames = []

    for csv_path in csv_files:
        df = pd.read_csv(csv_path)
        n_original = len(df)

        if subsample_per_file is not None and n_original > subsample_per_file:
            idx = rng.choice(n_original, size=subsample_per_file, replace=False)
            df = df.iloc[idx].reset_index(drop=True)

        frames.append(df)
        fname = os.path.basename(csv_path)
        print(f"  [Load] {fname}: {n_original} rows"
              + (f" -> subsampled to {len(df)}" if len(df) < n_original else ""))

    combined = pd.concat(frames, ignore_index=True)
    print(f"  [Load] Total: {len(combined)} rows")

    # Print class distribution
    label_counts = combined[LABEL_COL].value_counts()
    print(f"  [Load] Benign: {label_counts.get(0, 0)}, "
          f"Attack: {label_counts.get(1, 0)}")

    return combined


# ============================================================================
# Preprocessing
# ============================================================================

def preprocess_cic(train_df, test_df=None, test_size=0.2, seed=42):
    """
    Preprocess CIC dataset(s) for binary classification.

    If test_df is None, splits train_df into train/test (stratified).
    If test_df is provided (same or different domain), uses it directly.
    Scaler is always fitted on training data only.

    Handles CICFlowMeter data quality issues:
    - Replaces Infinity values with NaN (Flow Bytes/s, Flow Packets/s
      can be Inf when Flow Duration=0)
    - Fills NaN with training set medians
    - Clips scaled values to [0, 1]

    Args:
        train_df: Training DataFrame (with all 85 columns)
        test_df: Optional test DataFrame (for cross-dataset or explicit split)
        test_size: Train/test split ratio (used only when test_df is None)
        seed: Random seed
    Returns:
        X_train, y_train, X_test, y_test: numpy arrays (float32)
        scaler: fitted MinMaxScaler
        feature_dim: int (number of features, should be 79)
        train_attack_names: numpy array of attack name strings
        test_attack_names: numpy array of attack name strings
    """
    # Split if no test_df provided
    if test_df is None:
        train_df, test_df = train_test_split(
            train_df, test_size=test_size, random_state=seed,
            stratify=train_df[LABEL_COL]
        )
        train_df = train_df.reset_index(drop=True)
        test_df = test_df.reset_index(drop=True)

    # Extract labels (already binary 0/1)
    y_train = train_df[LABEL_COL].values.astype(int)
    y_test = test_df[LABEL_COL].values.astype(int)

    # Extract attack names (for customized distribution)
    train_attack_names = train_df[ATTACK_NAME_COL].values
    test_attack_names = test_df[ATTACK_NAME_COL].values

    # Drop metadata and label columns
    drop_cols = METADATA_COLS + [ATTACK_NAME_COL, LABEL_COL]
    train_features = train_df.drop(columns=drop_cols, errors='ignore')
    test_features = test_df.drop(columns=drop_cols, errors='ignore')

    # Align test columns to match train column order (defensive for cross-dataset)
    test_features = test_features.reindex(columns=train_features.columns)

    # Convert to float32
    train_features = train_features.astype(np.float32)
    test_features = test_features.astype(np.float32)

    # Handle Infinity and NaN values
    # CICFlowMeter produces Inf when Flow Duration=0 (division by zero)
    train_features = train_features.replace([np.inf, -np.inf], np.nan)
    test_features = test_features.replace([np.inf, -np.inf], np.nan)

    # Fill NaN with training set medians (train medians used for both)
    train_medians = train_features.median()
    train_features = train_features.fillna(train_medians)
    test_features = test_features.fillna(train_medians)

    n_train_nan = train_features.isna().sum().sum()
    n_test_nan = test_features.isna().sum().sum()
    if n_train_nan > 0 or n_test_nan > 0:
        print(f"  [Warning] Remaining NaN after fill: train={n_train_nan}, test={n_test_nan}")
        train_features = train_features.fillna(0)
        test_features = test_features.fillna(0)

    X_train = train_features.values
    X_test = test_features.values

    # Normalize with MinMaxScaler (fitted on training data only)
    scaler = MinMaxScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # Clip test data to [0, 1] (cross-dataset values may exceed training range)
    X_test = np.clip(X_test, 0.0, 1.0)

    feature_dim = X_train.shape[1]

    print(f"[Preprocessing] Feature dimension: {feature_dim}")
    print(f"[Preprocessing] Training samples: {len(X_train)}")
    print(f"[Preprocessing] Testing samples: {len(X_test)}")
    print(f"[Preprocessing] Train labels: Benign={np.sum(y_train==0)}, "
          f"Attack={np.sum(y_train==1)}")
    print(f"[Preprocessing] Test labels: Benign={np.sum(y_test==0)}, "
          f"Attack={np.sum(y_test==1)}")

    return (X_train, y_train, X_test, y_test, scaler, feature_dim,
            train_attack_names, test_attack_names)


# ============================================================================
# Customized Data Distribution
# ============================================================================

def distribute_data_customized_iomt(attack_names, y_train, X_processed, seed=42):
    """
    Customized distribution for CIC-IoMT-2024 (2 agents).

    Agent 0: Benign + DoS/DDoS attacks
    Agent 1: Benign + MQTT + Recon + MITM attacks

    Args:
        attack_names: Array of attack name strings for each training sample
        y_train: Binary labels
        X_processed: Processed feature matrix
        seed: Random seed
    Returns:
        List of (X_agent, y_agent) tuples
    """
    categories = np.array([IOMT_ATTACK_CATEGORIES.get(name, 'Unknown')
                           for name in attack_names])

    # Agent 0: Benign + DoS/DDoS
    agent0_mask = np.isin(categories, ['Benign', 'DoS_DDoS'])
    # Agent 1: Benign + MQTT/Recon/MITM
    agent1_mask = np.isin(categories, ['Benign', 'MQTT_Recon_MITM'])

    agent_data = [
        (X_processed[agent0_mask], y_train[agent0_mask]),
        (X_processed[agent1_mask], y_train[agent1_mask]),
    ]

    for i, (X_a, y_a) in enumerate(agent_data):
        print(f"[Customized Distribution IoMT] Agent {i}: {len(X_a)} samples "
              f"(Benign: {np.sum(y_a==0)}, Attack: {np.sum(y_a==1)})")

    return agent_data


def distribute_data_customized_iiot(attack_names, y_train, X_processed, seed=42):
    """
    Customized distribution for CIC-Edge-IIoTSet-2022 (2 agents).

    Agent 0: Benign + DDoS/DoS attacks
    Agent 1: Benign + Application-layer attacks

    Args:
        attack_names: Array of attack name strings for each training sample
        y_train: Binary labels
        X_processed: Processed feature matrix
        seed: Random seed
    Returns:
        List of (X_agent, y_agent) tuples
    """
    categories = np.array([IIOT_ATTACK_CATEGORIES.get(name, 'Unknown')
                           for name in attack_names])

    # Agent 0: Benign + DDoS/DoS
    agent0_mask = np.isin(categories, ['Benign', 'DDoS_DoS'])
    # Agent 1: Benign + Application attacks
    agent1_mask = np.isin(categories, ['Benign', 'Application'])

    agent_data = [
        (X_processed[agent0_mask], y_train[agent0_mask]),
        (X_processed[agent1_mask], y_train[agent1_mask]),
    ]

    for i, (X_a, y_a) in enumerate(agent_data):
        print(f"[Customized Distribution IIoT] Agent {i}: {len(X_a)} samples "
              f"(Benign: {np.sum(y_a==0)}, Attack: {np.sum(y_a==1)})")

    return agent_data
